### ISSUE TITLE
Demo / instructions for local setup

### ISSUE THREAD

**Issue by srph** [CalebMorris/centipede#1]
You have an interesting work here :sparkles:. Do you mind setting up a GH-page for this or an instruction for local setup? Thanks.

**Comment by CalebMorris** [comment]
@srph Sure.
The project is severely out of date and uses deprecated APIs from Dart so I need to update that first before adding a demo and local instructions.

**Comment by CalebMorris** [comment]
I added instructions to get it build in JS and deploy locally.
Let me know if you have any problems getting it to run (I'm still unfamiliar with Dart).

**Comment by CalebMorris** [comment]
Demo up on readme

**Comment by srph** [comment]
Thanks! :+1:
